/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myapp;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int test;
        Klasse ttt = new Klasse(22);

        test= ttt.getAge();
        System.out.println(test);
    }

}
